name: "NetworkPlayerCount"
author: "xxAROX"
website: "https://github.com/xxAROX/"
version: "1.0"
description: "NetworkPlayerCount plugin by xxAROX."

api: [ "3.0.0" ]
main: xxAROX\NetworkPlayerCount\Main
